### ISSUE TITLE
Question about baseline

### ISSUE THREAD

**Issue by melgor** [Confusezius/CVPR2020_PADS#1]
Hi,
looking into your results you have very powerful Triplet-Semihad baseline (20% more that other paper). 
Few question about that:
- do you have intuition why it is so strong? Different Sampler? Different hyperparameters (beside embedding dim)?
- also I noted that score for Triplet-Semihard is 72% in paper, but is [this repo](https://github.com/Confusezius/Deep-Metric-Learning-Baselines) there is 75.4%? What are the differences between this two runs? Shouldn't they be the same?

**Comment by Confusezius** [comment]
Hi there!

Regarding the first point: There are multiple things that play a relevant role: 
(1) We use a triplet margin value of 0.2 where as previous implementations used a value of 1, which already made a notable difference.
(2) The setup of the batch to include a fixed number of samples per class will also impact performance.
(3) We use a ResNet-50 compared to potentially a GoogLeNet.
All these factors contribute to a significant boost in performance. 

Regarding the second point:
The results in our paper are indeed correct and were computed with semihard sampling (the current semihard implementation in the linked repo). The results in the Deep-Metric-Learning-Baselines Repository were mislabelled and computed with a soft version of hard tuple sampling - I have corrected the labelling there as well. Thanks for pointing that out!
